### ISSUE TITLE
TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_3__.use) is not a function

### ISSUE THREAD

**Issue by Shadowh4k** [shuding/next-view-transitions#30]
If my project have this structure: 
![image](https://github.com/user-attachments/assets/3d2bcac8-97f4-40c9-8ba6-422129e07f05)

I got this error:
![image](https://github.com/user-attachments/assets/4186117c-4e89-43f8-b482-9eb8fce52889)

I tried to fix it but i need some help

**Comment by shuding** [comment]
This library requires Next.js **App Router**, because it relies on some layout and router features. This is also mentioned in the README.
