### ISSUE TITLE
Does `ViewTransitions` need to directly wrap `<html>`?

### ISSUE THREAD

**Issue by lancejpollard** [shuding/next-view-transitions#33]
Does `ViewTransitions` need to directly wrap `<html>`? Or can it instead wrap a tree of providers and other stuff? I am doing this but nothing is happening:

```tsx
import { ViewTransitions } from 'next-view-transitions'

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ViewTransitions>
      <MyProviderTree>{children}</MyProviderTree>
    </ViewTransitions>
  )
}
```

Somewhere in the provider tree is the `<html>` tag eventually.

Thoughts on getting this to work?

**Comment by shuding** [comment]
It doesn't need to wrap the `<html>`, but it should cover all `Link` and `useTransitionRouter` usage.
