### ISSUE TITLE
I am always getting this error in Next15. please help

### ISSUE THREAD

**Issue by kovacsIVgabor** [shuding/next-view-transitions#49]
```
Error: Cannot find module '/home/user/myproject/node_modules/next/link' imported from /home/user/myproject/node_modules/next-view-transitions/dist/index.js
Did you mean to import "next/link.js"?
```
Maybe it is because I don't use the app folder? I use the Next12 style `pages` folder.
Please help me. I would really like to use this feature.

**Comment by MatanBobi** [comment]
AFAIU, this library only supports the App router.

**Comment by shuding** [comment]
Unfortunately this library only supports App Router, it's mentioned in the README.
