### ISSUE TITLE
client-side exception

### ISSUE THREAD

**Issue by KevinDoughty** [shuding/next-view-transitions#7]
Steps to reproduce:
Click "Go to / demo" and "Open homepage" back and forth a dozen times. Then hit the browser's back navigation button, rapidly, a dozen times. If it doesn’t crash, hit the browser's forward navigation button, rapidly, a dozen times. It usually crashes on me before that.

Using Brave, Ubuntu
![Screenshot from 2024-04-14 20-41-59](https://github.com/shuding/next-view-transitions/assets/1807709/82c7584a-f5ee-4eff-8369-2be3fc258d18)

**Comment by KevinDoughty** [comment]
Ran it in dev mode on my machine
![Screenshot from 2024-04-17 11-45-39](https://github.com/shuding/next-view-transitions/assets/1807709/5d6aea85-3663-48f2-a4e9-1ce823e4fff8)

**Comment by KevinDoughty** [comment]
I don't think it's possible to disable HMR in Next for a minimal reproduction to get rid of the "Warning: Cannot update a component (`HotReload`) while rendering a different component (`ViewTransitions`)."

That stack trace can probably be disregarded though. The async/await trace looks like this:
```
react-dom.development.js:9157 Uncaught Error: async/await is not yet supported in Client Components, only Server Components. This error is often caused by accidentally adding `'use client'` to a module that was originally written for the server.
    at trackUsedThenable (react-dom.development.js:9157:19)
    at useThenable (react-dom.development.js:11483:16)
    at Object.use (react-dom.development.js:11504:14)
    at use (react.development.js:2572:21)
    at useBrowserNativeTransitions (index.js:47:12)
    at ViewTransitions (index.js:80:5)
    at renderWithHooks (react-dom.development.js:11121:18)
    at updateFunctionComponent (react-dom.development.js:16290:20)
    at beginWork$1 (react-dom.development.js:18472:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:20565:14)
    at Object.invokeGuardedCallbackImpl (react-dom.development.js:20614:16)
    at invokeGuardedCallback (react-dom.development.js:20689:29)
    at beginWork (react-dom.development.js:26949:7)
    at performUnitOfWork (react-dom.development.js:25748:12)
    at workLoopSync (react-dom.development.js:25464:5)
    at renderRootSync (react-dom.development.js:25419:7)
    at performSyncWorkOnRoot (react-dom.development.js:24887:20)
    at flushSyncWorkAcrossRoots_impl (react-dom.development.js:7758:13)
    at flushSyncWorkOnAllRoots (react-dom.development.js:7718:3)
    at processRootScheduleInMicrotask (react-dom.development.js:7863:3)
    at eval (react-dom.development.js:8034:7)
trackUsedThenable	@	react-dom.development.js:9157
useThenable	@	react-dom.development.js:11483
use	@	react-dom.development.js:11504
use	@	react.development.js:2572
useBrowserNativeTransitions	@	index.js:47
ViewTransitions	@	index.js:80
renderWithHooks	@	react-dom.development.js:11121
updateFunctionComponent	@	react-dom.development.js:16290
beginWork$1	@	react-dom.development.js:18472
callCallback	@	react-dom.development.js:20565
invokeGuardedCallbackImpl	@	react-dom.development.js:20614
invokeGuardedCallback	@	react-dom.development.js:20689
beginWork	@	react-dom.development.js:26949
performUnitOfWork	@	react-dom.development.js:25748
workLoopSync	@	react-dom.development.js:25464
renderRootSync	@	react-dom.development.js:25419
performSyncWorkOnRoot	@	react-dom.development.js:24887
flushSyncWorkAcrossRoots_impl	@	react-dom.development.js:7758
flushSyncWorkOnAllRoots	@	react-dom.development.js:7718
processRootScheduleInMicrotask	@	react-dom.development.js:7863
eval	@	react-dom.development.js:8034
```

**Comment by mpopv** [comment]
Same here in Chrome.

Originates at: https://github.com/shuding/next-view-transitions/blob/61d220bc4a1d81697011a7a3e1c4867b4826a329/src/browser-native-events.ts#L65
```
  if (transition && currentPathname.current !== pathname) {
    // Whenever the pathname changes, we block the rendering of the new route
    // until the view transition is started (i.e. DOM screenshotted).
>>  use(transition[0])
  }
```

**Comment by boombb12138** [comment]
I think the issue maybe related to the "use" hook.
![image](https://github.com/shuding/next-view-transitions/assets/95857565/f2a19d84-92f8-465a-a14c-0d7595206a6d)
React sugguests that we should generate the promise in server component, while here the transition[0] is generated in client side and relayed on browser API. 
![image](https://github.com/shuding/next-view-transitions/assets/95857565/491eb583-0e22-49fa-9ea7-27a9ff0a2d9d)
So the solution maybe passing a context rather than promise to the use hook.
I am still trying to fix it :) 
Metion this in case the duplicated work :)

**Comment by boombb12138** [comment]
Fixed ~
![GIF 2024-4-22 11-46-13](https://github.com/shuding/next-view-transitions/assets/95857565/b18f5759-d69f-4a40-b3cb-97e54132ae1d)
I cleaning up the event listener, and everything goes well. 
![image](https://github.com/shuding/next-view-transitions/assets/95857565/18be8a1a-e22a-4662-b792-3cd3ac9b35ec)
Could you please tell me the issue that may caused by clean up the listener? I don't figure out the potential problems. @shuding

**Comment by KevinDoughty** [comment]
I can confim https://github.com/shuding/next-view-transitions/pull/8 fixes the client-side exception, but it also completely disables all animation on browser navigation (using the forward and backward button instead of clicking the links).

It’s not a failure by Next, I think animation is just too hard of a problem for the W3C and the fault lies with the spec.

**Comment by KevinDoughty** [comment]
I can confim https://github.com/shuding/next-view-transitions/pull/8 fixes the client-side exception, but it also completely disables all animation on browser navigation (using the forward and backward button instead of clicking the links).

I think the fault lies with the View-Transitions spec, but will be happy if you can prove me wrong.

**Comment by shuding** [comment]
Yes like @KevinDoughty said, I noticed that once removed the event listener in `useSyncExternalStore` it won't be registered again upon re-rendering. That breaks the browser navigation transitions. And that's why I removed it.

I wasn't sure if it's a React or a Next.js issue and didn't have the time to dig into it.

**Comment by javascripter** [comment]
@shuding cc @KevinDoughty @boombb12138 
I submitted a [PR](https://github.com/shuding/next-view-transitions/pull/11) that fixes this issue & maintain browser navigation transitions.
Can you take a look and see if my approach looks good? My approach removes `useSyncExternalStore` and uses useState + useEffect instead

**Comment by KevinDoughty** [comment]
Verified, the [https://github.com/shuding/next-view-transitions/pull/11](PR) submitted by @javascripter works on my machine. I cannot cause a client-side exception no matter how hard I try.

Google dev rel Bramus mentioned on the site formerly known as Bird that they are working on making View Transitions retargetable, which should mean the following visual discrepancies will be fixed. I suspect the API and behavioral impact will be minimal, but will investigate when the time comes.

https://github.com/shuding/next-view-transitions/assets/1807709/be13d685-f130-4ed6-96ba-cf916efd18b8
